name: Déclencher un workflow externe

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Déclencher le workflow externe
        uses: actions/checkout@v2
        with:
          repository: utilisateur/repo-b
          ref: main
          token: ${{ secrets.REPO_B_TOKEN }} # Utilisez le secret ici
        # Vous pouvez également ajouter d'autres étapes ici si nécessaire
