name: Déclencher un workflow externe

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: Omaraitbenhaddi/node.js-express-firstAPI # Replace with the target repo owner and name
          ref: main # Replace with the target branch in repo B
          token: ${{ secrets.GITHUB_TOKEN }}
      # You can also add other steps here if needed
