name: Déclencher un workflow externe

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Déclencher le workflow externe
        uses: actions/checkout@v2
        with:
          repository: Omaraitbenhaddi/node.js-express-firstAPI
          ref: main 
